[package]
name = "SHUtils"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
dirs = "5.0.1"
iced = { version = "0.13.1", features = ["image", "advanced", "svg"] }
serde = { version = "1.0.210", features = ["derive"] }
